{{- if .Values.ingressRoute.enabled -}}
{{- $labServiceName := include "memgraph.labServiceName" . -}}
{{- $defaultHostUrl := include "memgraph.defaultHostUrl" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "memgraph.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memgraph.labels" . | nindent 4 }}
  annotations:
    link.argocd.argoproj.io/external-link: https://{{ $defaultHostUrl }}
  {{- with .Values.ingressRoute.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  {{- if .Values.ingressRoute.tls }}
  tls:
    secretName: {{ .Values.ingressRoute.tls.secretName }}
  {{- end }}
  routes:
    {{- range .Values.ingressRoute.hosts }}
    - match: Host(`{{ .host | default $defaultHostUrl }}`)
      kind: Rule
      services:
        - name: {{ $labServiceName }}
          port: {{ (index $.Values "memgraph-lab" "service" "port") | default 3000 }}
      middlewares:
        - name: traefik-traefik-forward-auth@kubernetescrd
    {{- end }}
{{- end }}
