{{- $imageName := $.Values.image.repository -}}
{{- if $.Values.platform.enabled }}
{{- $imageName = print $imageName "-platform" -}}
{{- end}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "memgraph.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "memgraph.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "memgraph.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "memgraph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "memgraph.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "memgraph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/lib/memgraph/memgraph"]
          ports:
            - name: bolt
              containerPort: 7687
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.platform.enabled }}
        - name: {{ .Chart.Name }}-platform
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "/lab/dist-backend/server.js"]
          workingDir: "/lab"
          ports:
            - name: platform
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: platform
          readinessProbe:
            httpGet:
              path: /
              port: platform
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
