apiVersion: v2
name: memgraph
description: Umbrella Helm chart for Memgraph (standalone + Lab) on Kubernetes
type: application
version: 0.2.0
# renovate: image=memgraph/memgraph-mage
appVersion: "3.9.0"
maintainers:
  - name: enys
dependencies:
  - name: memgraph
    version: 0.2.17
    repository: https://memgraph.github.io/helm-charts
  - name: memgraph-lab
    version: 0.1.15
    repository: https://memgraph.github.io/helm-charts
