apiVersion: v2
name: memgraph
description: Umbrella Helm chart for Memgraph (standalone + Lab) on Kubernetes
type: application
version: 0.2.0
# renovate: image=memgraph/memgraph-mage
appVersion: "3.9.0"
maintainers:
  - name: enys
dependencies:
  - name: memgraph
    version: 0.2.18
    repository: https://memgraph.github.io/helm-charts
    # repository: file:///Users/enys/projets/repos/infra/memgraph-helm-charts/charts/memgraph
  - name: memgraph-lab
    version: 0.1.16
    # repository: file:///Users/enys/projets/repos/infra/memgraph-helm-charts/charts/memgraph-lab
    repository: https://memgraph.github.io/helm-charts
